'use client';
import { ExternalLink, Globe2, KeyRound, LockKeyhole, RefreshCw, Router, ShieldCheck, Wifi } from 'lucide-react';
import { useEffect, useState } from 'react';
type Status={configured:boolean;domain:string;canManage?:boolean;dnsUpdatedAt?:string;dnsOk?:boolean;caddyOk?:boolean;publicOk?:boolean;httpsOk?:boolean;socketOk?:boolean;message?:string};
type Gate={configured:boolean;enabled:boolean};
export function RemoteAccessPanel(){const[domain,setDomain]=useState('');const[token,setToken]=useState('');const[pin,setPin]=useState('');const[status,setStatus]=useState<Status>({configured:false,domain:''});const[gate,setGate]=useState<Gate>({configured:false,enabled:false});const[busy,setBusy]=useState(false);
async function load(){const[r,g]=await Promise.all([fetch('/api/remote-access',{cache:'no-store'}),fetch('/api/access-gate',{cache:'no-store'})]);if(r.ok){const n=await r.json() as Status;setStatus(n);if(n.domain)setDomain(n.domain.replace(/\.duckdns\.org$/i,''));}if(g.ok)setGate(await g.json() as Gate);}useEffect(()=>{void load();},[]);
async function save(){setBusy(true);try{const r=await fetch('/api/remote-access',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({provider:'duckdns',domain,token})});const n=await r.json() as Status&{error?:string};if(!r.ok)throw new Error(n.error||'Could not configure remote access.');setToken('');setStatus(n);}catch(e){setStatus(c=>({...c,message:e instanceof Error?e.message:'Could not configure remote access.'}));}finally{setBusy(false);}}
async function savePin(){setBusy(true);try{const r=await fetch('/api/access-gate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pin})});const n=await r.json() as Gate&{error?:string};if(!r.ok)throw new Error(n.error||'Could not save access PIN.');setGate(n);setPin('');setStatus(c=>({...c,message:'Private access PIN saved. Public visitors must unlock the table first.'}));}catch(e){setStatus(c=>({...c,message:e instanceof Error?e.message:'Could not save access PIN.'}));}finally{setBusy(false);}}
async function check(){setBusy(true);try{const r=await fetch('/api/remote-access/check',{method:'POST'});const n=await r.json() as Status;setStatus(current=>({...current,...n,canManage:current.canManage}));}finally{setBusy(false);}}
const canManage=status.canManage===true;
return <section className="rounded-3xl border border-cyan-300/20 bg-cyan-300/[.045] p-4 shadow-2xl"><div className="flex items-start gap-3"><div className="rounded-2xl bg-cyan-300/10 p-3 text-cyan-200"><Globe2 size={22}/></div><div><div className="font-black">REMOTE ACCESS</div><div className="mt-1 text-xs leading-5 text-zinc-400">Connect this install to its own DuckDNS address. DNS credentials and host configuration stay on your local network.</div></div></div>
{canManage?<div className="mt-4 space-y-3"><label className="block"><span className="mb-1 block text-[10px] font-black uppercase tracking-wider text-zinc-500">DuckDNS subdomain</span><div className="flex overflow-hidden rounded-xl border border-white/10 bg-black/25"><input value={domain} onChange={e=>setDomain(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,''))} placeholder="mtgtable" className="min-w-0 flex-1 bg-transparent px-3 py-3 text-sm outline-none"/><span className="flex items-center border-l border-white/10 px-3 text-xs text-zinc-500">.duckdns.org</span></div></label><label className="block"><span className="mb-1 flex items-center gap-1 text-[10px] font-black uppercase tracking-wider text-zinc-500"><KeyRound size={11}/> DuckDNS token</span><input type="password" value={token} onChange={e=>setToken(e.target.value.trim())} placeholder={status.configured?'Saved — enter only to replace':'Paste DuckDNS token'} className="w-full rounded-xl border border-white/10 bg-black/25 px-3 py-3 text-sm outline-none"/></label><button disabled={busy||!domain||(!token&&!status.configured)} onClick={()=>void save()} className="w-full rounded-xl bg-cyan-300 py-3 text-xs font-black text-zinc-950 disabled:opacity-40">{busy?'WORKING…':status.configured?'UPDATE REMOTE ACCESS':'ENABLE REMOTE ACCESS'}</button></div>:<div className="mt-4 rounded-2xl border border-white/10 bg-black/20 p-3"><div className="text-[10px] font-black uppercase tracking-[.16em] text-zinc-400">Local admin only</div><div className="mt-1 text-xs leading-5 text-zinc-500">DuckDNS settings can only be viewed or changed from this Umbrel's local address. Public visitors cannot change the domain or token.</div></div>}
<div className="mt-4 border-t border-white/10 pt-4"><div className="mb-2 flex items-center gap-2 text-xs font-black"><LockKeyhole size={14}/> PRIVATE PUBLIC ACCESS</div><div className="text-[11px] leading-5 text-zinc-500">Set a 4–8 digit PIN. Anyone visiting the public address must enter it; no Umbrel account is required.</div><div className="mt-2 flex gap-2"><input type="password" inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,8))} placeholder={gate.enabled?'PIN enabled — enter new PIN to change':'4–8 digit PIN'} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/25 px-3 py-3 text-sm outline-none"/><button disabled={busy||pin.length<4} onClick={()=>void savePin()} className="rounded-xl bg-white/10 px-4 text-xs font-black disabled:opacity-40">{gate.enabled?'CHANGE':'SET PIN'}</button></div>{gate.enabled&&<div className="mt-2 text-[10px] font-black uppercase tracking-wider text-emerald-300">✓ Public PIN protection enabled</div>}</div>
{status.configured&&<div className="mt-4 rounded-2xl border border-white/10 bg-black/20 p-3"><div className="flex items-center justify-between gap-2"><div className="truncate text-sm font-black">{status.domain}</div><button onClick={()=>void check()} disabled={busy} className="rounded-lg bg-white/10 p-2 text-zinc-300"><RefreshCw size={14} className={busy?'animate-spin':''}/></button></div><div className="mt-3 grid grid-cols-2 gap-2 text-[10px] font-black uppercase"><Badge icon={<Globe2 size={12}/>} label="DNS" ok={status.dnsOk}/><Badge icon={<ShieldCheck size={12}/>} label="HTTPS Proxy" ok={status.caddyOk}/><Badge icon={<Wifi size={12}/>} label="Public" ok={status.publicOk}/><Badge icon={<ShieldCheck size={12}/>} label="HTTPS" ok={status.httpsOk}/><Badge icon={<Wifi size={12}/>} label="Socket.IO" ok={status.socketOk}/></div>{status.caddyOk&&!status.publicOk&&<div className="mt-3 rounded-xl bg-white/[.04] p-3 text-[10px] leading-5 text-zinc-400"><div className="mb-1 flex items-center gap-1 font-black uppercase text-zinc-300"><Router size={12}/> Router setup</div>Forward WAN TCP 80 → Umbrel port 18080<br/>Forward WAN TCP 443 → Umbrel port 18443</div>}{status.httpsOk&&status.domain&&<a href={`https://${status.domain}`} target="_blank" rel="noreferrer" className="mt-3 flex items-center justify-center gap-2 rounded-xl bg-white/10 py-2.5 text-xs font-black">OPEN REMOTE TABLE <ExternalLink size={13}/></a>}</div>}{status.message&&<div className="mt-3 text-[11px] leading-5 text-zinc-400">{status.message}</div>}<p className="mt-3 text-[10px] leading-4 text-zinc-600">The app handles DuckDNS, HTTPS termination, PIN access, and Socket.IO. Your router still must route WAN ports 80/443 to this Umbrel install.</p></section>}
function Badge({icon,label,ok}:{icon:React.ReactNode;label:string;ok?:boolean}){return <div className={`flex items-center gap-2 rounded-xl px-3 py-2 ${ok?'bg-emerald-400/10 text-emerald-200':'bg-white/5 text-zinc-500'}`}>{icon}{label}<span className="ml-auto">{ok?'✓':'—'}</span></div>}
