'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';

type CounterKey='poison'|'energy'|'experience'|'storm'|'commanderTax';
type UtilityPlayer={id:string;name:string;life:number;poison:number;energy:number;experience:number;storm:number;commanderTax:number;commanderDamage:Record<string,number>};
type UtilityState={players:UtilityPlayer[];startingLife:number;activePlayerId?:string;monarchId?:string;initiativeId?:string;seconds:number;running:boolean;turn:number;started:boolean};

const STORAGE_KEY='mtg-practice-utility-v2';
const COLORS=['#f43f5e','#3b82f6','#f59e0b','#22c55e','#a855f7','#06b6d4','#ec4899','#84cc16','#f97316','#64748b'];
const uid=()=>typeof crypto!=='undefined'&&'randomUUID' in crypto?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
function makePlayer(index:number,life:number):UtilityPlayer{return{id:uid(),name:`Player ${index+1}`,life,poison:0,energy:0,experience:0,storm:0,commanderTax:0,commanderDamage:{}}}
function freshState(count:number,life:number):UtilityState{return{players:Array.from({length:count},(_,index)=>makePlayer(index,life)),startingLife:life,seconds:0,running:false,turn:1,started:true}}
function formatTime(total:number){const minutes=Math.floor(total/60),seconds=total%60;return `${minutes}:${String(seconds).padStart(2,'0')}`}

export default function UtilityPage(){
 const router=useRouter();
 const [setupPlayers,setSetupPlayers]=useState(4),[setupLife,setSetupLife]=useState(40),[customLife,setCustomLife]=useState(40);
 const [state,setState]=useState<UtilityState>();
 const [menuOpen,setMenuOpen]=useState(false),[detailId,setDetailId]=useState<string>(),[diceResult,setDiceResult]=useState<string>(),[editingId,setEditingId]=useState<string>();

 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)setState(JSON.parse(raw) as UtilityState)}catch{/* ignore */}},[]);
 useEffect(()=>{if(state)localStorage.setItem(STORAGE_KEY,JSON.stringify(state))},[state]);
 useEffect(()=>{if(!state?.running)return;const timer=window.setInterval(()=>setState(current=>current?{...current,seconds:current.seconds+1}:current),1000);return()=>window.clearInterval(timer)},[state?.running]);
 const detailed=state?.players.find(player=>player.id===detailId);
 const defeated=useMemo(()=>new Set(state?.players.filter(player=>player.life<=0||player.poison>=10||Object.values(player.commanderDamage).some(value=>value>=21)).map(player=>player.id)??[]),[state]);

 function patchPlayer(id:string,fn:(player:UtilityPlayer)=>UtilityPlayer){setState(current=>current?{...current,players:current.players.map(player=>player.id===id?fn(player):player)}:current)}
 function life(id:string,delta:number){patchPlayer(id,player=>({...player,life:player.life+delta}))}
 function counter(id:string,key:CounterKey,delta:number){patchPlayer(id,player=>({...player,[key]:Math.max(0,player[key]+delta)}))}
 function commanderDamage(targetId:string,sourceId:string,delta:number){patchPlayer(targetId,player=>{const next=Math.max(0,(player.commanderDamage[sourceId]??0)+delta);return{...player,life:player.life-delta,commanderDamage:{...player.commanderDamage,[sourceId]:next}}})}
 function quit(){localStorage.removeItem(STORAGE_KEY);router.push('/')}
 function reset(){if(state)setState(freshState(state.players.length,state.startingLife));setMenuOpen(false)}
 function nextTurn(){setState(current=>{if(!current)return current;const alive=current.players.filter(player=>!defeated.has(player.id));if(!alive.length)return current;const currentIndex=Math.max(-1,alive.findIndex(player=>player.id===current.activePlayerId));const next=alive[(currentIndex+1)%alive.length];return{...current,activePlayerId:next.id,turn:current.turn+1,players:current.players.map(player=>({...player,storm:0}))}})}

 if(!state?.started)return <main className="flex min-h-[100dvh] items-center justify-center bg-[#090b0d] px-5 py-8 text-white"><section className="w-full max-w-md rounded-[2rem] border border-white/10 bg-white/[.04] p-5 shadow-2xl"><button onClick={()=>router.push('/')} className="mb-5 rounded-xl bg-white/5 px-3 py-2 text-sm font-bold text-zinc-300">← Main Menu</button><div className="text-[11px] font-black uppercase tracking-[.24em] text-cyan-300">Table Utility</div><h1 className="mt-1 text-3xl font-black">Start Table</h1><p className="mt-2 text-sm leading-6 text-zinc-400">Designed for a phone or tablet lying flat between players.</p><div className="mt-6 space-y-4"><label className="flex items-center justify-between font-bold">Players<select value={setupPlayers} onChange={event=>setSetupPlayers(Number(event.target.value))} className="rounded-xl border border-white/10 bg-zinc-900 px-3 py-2">{Array.from({length:9},(_,index)=>index+2).map(value=><option key={value}>{value}</option>)}</select></label><label className="flex items-center justify-between font-bold">Starting life<select value={setupLife} onChange={event=>setSetupLife(Number(event.target.value))} className="rounded-xl border border-white/10 bg-zinc-900 px-3 py-2"><option value={20}>20</option><option value={30}>30</option><option value={40}>40</option><option value={0}>Custom</option></select></label>{setupLife===0&&<input type="number" min={1} value={customLife} onChange={event=>setCustomLife(Number(event.target.value)||1)} className="w-full rounded-xl border border-white/10 bg-black/25 px-3 py-3"/>}<button onClick={()=>setState(freshState(setupPlayers,setupLife===0?customLife:setupLife))} className="w-full rounded-2xl bg-cyan-300 py-4 text-base font-black text-zinc-950">START COUNTER</button></div></section></main>;

 const count=state.players.length;
 return <main className="relative h-[100dvh] w-screen overflow-hidden bg-black text-white [touch-action:manipulation] [user-select:none]">
  <section className={layoutClass(count)}>
   {state.players.map((player,index)=><PlayerZone key={player.id} player={player} index={index} count={count} color={COLORS[index%COLORS.length]} defeated={defeated.has(player.id)} active={state.activePlayerId===player.id} monarch={state.monarchId===player.id} initiative={state.initiativeId===player.id} onLife={delta=>life(player.id,delta)} onDetails={()=>setDetailId(player.id)} onEdit={()=>setEditingId(player.id)}/>) }
  </section>

  <button aria-label="Open table menu" onClick={()=>setMenuOpen(true)} className="absolute left-1/2 top-1/2 z-30 flex h-14 w-14 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-2xl border border-white/20 bg-[#121416]/95 text-xl font-black shadow-2xl backdrop-blur active:scale-95 sm:h-16 sm:w-16">☰</button>

  {menuOpen&&<div className="absolute inset-0 z-50 flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm" onClick={()=>setMenuOpen(false)}><section onClick={event=>event.stopPropagation()} className="w-full max-w-md rounded-[2rem] border border-white/10 bg-[#15181b] p-4 shadow-2xl"><div className="flex items-center justify-between"><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-300">Table Menu</div><div className="mt-1 text-xl font-black">Turn {state.turn} · {formatTime(state.seconds)}</div></div><button onClick={()=>setMenuOpen(false)} className="rounded-xl bg-white/5 px-3 py-2 font-black">✕</button></div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>setState(current=>current?{...current,running:!current.running}:current)} className="rounded-2xl bg-white/8 py-4 font-black">{state.running?'PAUSE TIMER':'START TIMER'}</button><button onClick={nextTurn} className="rounded-2xl bg-cyan-300 py-4 font-black text-zinc-950">NEXT TURN</button><button onClick={()=>setDiceResult(`D20: ${1+Math.floor(Math.random()*20)}`)} className="rounded-2xl bg-white/8 py-4 font-black">ROLL D20</button><button onClick={()=>setDiceResult(Math.random()<.5?'HEADS':'TAILS')} className="rounded-2xl bg-white/8 py-4 font-black">FLIP COIN</button></div>{diceResult&&<div className="mt-3 rounded-2xl bg-black/25 p-4 text-center text-3xl font-black">{diceResult}</div>}<div className="mt-4 grid grid-cols-2 gap-2"><button onClick={reset} className="rounded-2xl border border-white/10 py-3 text-sm font-black text-zinc-300">RESET</button><button onClick={quit} className="rounded-2xl border border-red-400/20 bg-red-400/5 py-3 text-sm font-black text-red-200">QUIT</button></div></section></div>}

  {detailed&&<div className="absolute inset-0 z-50 flex items-end justify-center bg-black/70 backdrop-blur-sm sm:items-center sm:p-4" onClick={()=>setDetailId(undefined)}><section onClick={event=>event.stopPropagation()} className="safe-bottom max-h-[82dvh] w-full overflow-y-auto rounded-t-[2rem] border border-white/10 bg-[#171a1d] p-4 sm:max-w-lg sm:rounded-[2rem]"><div className="flex items-center justify-between"><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-300">Player Controls</div><h2 className="text-2xl font-black">{detailed.name}</h2></div><button onClick={()=>setDetailId(undefined)} className="rounded-xl bg-white/5 px-3 py-2 font-black">✕</button></div><div className="mt-4 grid grid-cols-2 gap-2"><CounterControl label="Poison" value={detailed.poison} onMinus={()=>counter(detailed.id,'poison',-1)} onPlus={()=>counter(detailed.id,'poison',1)}/><CounterControl label="Energy" value={detailed.energy} onMinus={()=>counter(detailed.id,'energy',-1)} onPlus={()=>counter(detailed.id,'energy',1)}/><CounterControl label="Experience" value={detailed.experience} onMinus={()=>counter(detailed.id,'experience',-1)} onPlus={()=>counter(detailed.id,'experience',1)}/><CounterControl label="Storm" value={detailed.storm} onMinus={()=>counter(detailed.id,'storm',-1)} onPlus={()=>counter(detailed.id,'storm',1)}/><CounterControl label="Commander Tax" value={detailed.commanderTax} onMinus={()=>counter(detailed.id,'commanderTax',-2)} onPlus={()=>counter(detailed.id,'commanderTax',2)}/></div><div className="mt-4 space-y-2"><div className="text-[10px] font-black uppercase tracking-[.16em] text-zinc-500">Commander damage received</div>{state.players.filter(source=>source.id!==detailed.id).map(source=><div key={source.id} className="flex items-center justify-between rounded-xl bg-black/20 p-3"><span className="truncate font-bold">{source.name}</span><div className="flex items-center gap-2"><button onClick={()=>commanderDamage(detailed.id,source.id,-1)} className="h-10 w-10 rounded-xl bg-white/5 font-black">−</button><span className="w-14 text-center text-lg font-black">{detailed.commanderDamage[source.id]??0}</span><button onClick={()=>commanderDamage(detailed.id,source.id,1)} className="h-10 w-10 rounded-xl bg-red-400/15 font-black text-red-200">+</button></div></div>)}</div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>setState(current=>current?{...current,monarchId:current.monarchId===detailed.id?undefined:detailed.id}:current)} className={`rounded-2xl py-3 font-black ${state.monarchId===detailed.id?'bg-amber-300 text-zinc-950':'bg-white/5'}`}>♛ MONARCH</button><button onClick={()=>setState(current=>current?{...current,initiativeId:current.initiativeId===detailed.id?undefined:detailed.id}:current)} className={`rounded-2xl py-3 font-black ${state.initiativeId===detailed.id?'bg-violet-300 text-zinc-950':'bg-white/5'}`}>◆ INITIATIVE</button></div></section></div>}

  {editingId&&<LifeEditor player={state.players.find(player=>player.id===editingId)} onClose={()=>setEditingId(undefined)} onSave={(name,value)=>{patchPlayer(editingId,player=>({...player,name,life:value}));setEditingId(undefined)}}/>}
 </main>
}

function PlayerZone({player,index,count,color,defeated,active,monarch,initiative,onLife,onDetails,onEdit}:{player:UtilityPlayer;index:number;count:number;color:string;defeated:boolean;active:boolean;monarch:boolean;initiative:boolean;onLife:(delta:number)=>void;onDetails:()=>void;onEdit:()=>void}){
 const rotation=rotationFor(index,count);
 return <article style={{background:`linear-gradient(145deg,${color}ee,${color}aa)`}} className={`relative overflow-hidden ${active?'ring-4 ring-inset ring-white/80':''} ${defeated?'grayscale-[.5] brightness-50':''}`}>
  <div style={{transform:`rotate(${rotation}deg)`}} className="absolute inset-0 flex items-center justify-center transition-transform">
   <button aria-label={`Decrease ${player.name} life`} onClick={()=>onLife(-1)} className="absolute inset-y-0 left-0 w-1/2 active:bg-black/10"/>
   <button aria-label={`Increase ${player.name} life`} onClick={()=>onLife(1)} className="absolute inset-y-0 right-0 w-1/2 active:bg-white/10"/>
   <div className="pointer-events-none relative z-10 flex flex-col items-center justify-center text-center drop-shadow-lg"><div className="mb-1 flex items-center gap-2 text-[10px] font-black uppercase tracking-[.14em] text-white/75 sm:text-xs">{monarch&&<span>♛</span>}{initiative&&<span>◆</span>}<span>{player.name}</span></div><div className="text-[clamp(4.5rem,18vw,10rem)] font-black leading-none tabular-nums tracking-[-.06em]">{player.life}</div><div className="mt-1 flex items-center gap-3 text-xs font-black text-white/70"><span>−</span><span>tap sides</span><span>+</span></div>{defeated&&<div className="mt-2 rounded-full bg-black/35 px-3 py-1 text-xs font-black uppercase">Defeated</div>}</div>
   <button aria-label={`${player.name} details`} onClick={event=>{event.stopPropagation();onDetails()}} className="absolute bottom-3 left-3 z-20 flex h-10 w-10 items-center justify-center rounded-full bg-black/20 text-lg font-black backdrop-blur active:scale-95">•••</button>
   <button aria-label={`Edit ${player.name}`} onClick={event=>{event.stopPropagation();onEdit()}} className="absolute bottom-3 right-3 z-20 rounded-full bg-black/20 px-3 py-2 text-[10px] font-black uppercase backdrop-blur active:scale-95">Edit</button>
   {(player.poison>0||player.commanderTax>0)&&<div className="pointer-events-none absolute top-3 right-3 z-20 flex gap-1 text-[10px] font-black"><span className="rounded-full bg-black/25 px-2 py-1">☠ {player.poison}</span>{player.commanderTax>0&&<span className="rounded-full bg-black/25 px-2 py-1">Tax +{player.commanderTax}</span>}</div>}
  </div>
 </article>
}

function LifeEditor({player,onClose,onSave}:{player?:UtilityPlayer;onClose:()=>void;onSave:(name:string,life:number)=>void}){const [name,setName]=useState(player?.name??''),[life,setLife]=useState(player?.life??40);if(!player)return null;return <div className="absolute inset-0 z-[60] flex items-center justify-center bg-black/75 p-4"><section className="w-full max-w-sm rounded-[2rem] border border-white/10 bg-[#171a1d] p-5"><div className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-300">Edit Player</div><input value={name} onChange={event=>setName(event.target.value)} className="mt-3 w-full rounded-xl border border-white/10 bg-black/25 px-3 py-3 text-lg font-black outline-none"/><input type="number" value={life} onChange={event=>setLife(Number(event.target.value)||0)} className="mt-3 w-full rounded-xl border border-white/10 bg-black/25 px-3 py-4 text-center text-5xl font-black outline-none"/><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={onClose} className="rounded-xl bg-white/5 py-3 font-black">CANCEL</button><button onClick={()=>onSave(name.trim()||player.name,life)} className="rounded-xl bg-cyan-300 py-3 font-black text-zinc-950">SAVE</button></div></section></div>}
function CounterControl({label,value,onMinus,onPlus}:{label:string;value:number;onMinus:()=>void;onPlus:()=>void}){return <div className="rounded-2xl bg-black/20 p-3"><div className="text-center text-[10px] font-black uppercase tracking-wider text-zinc-500">{label}</div><div className="mt-2 grid grid-cols-[44px_1fr_44px] items-center gap-2"><button onClick={onMinus} className="h-11 rounded-xl bg-white/5 text-xl font-black">−</button><div className="text-center text-2xl font-black">{value}</div><button onClick={onPlus} className="h-11 rounded-xl bg-white/5 text-xl font-black">+</button></div></div>}
function layoutClass(count:number){if(count===2)return'grid h-full w-full grid-rows-2 gap-[2px] bg-black';if(count===3)return'grid h-full w-full grid-cols-2 grid-rows-2 gap-[2px] bg-black [&>*:first-child]:col-span-2';if(count===4)return'grid h-full w-full grid-cols-2 grid-rows-2 gap-[2px] bg-black';return`grid h-full w-full gap-[2px] bg-black ${count<=6?'grid-cols-2 grid-rows-3':count<=8?'grid-cols-2 grid-rows-4':'grid-cols-2 grid-rows-5'}`}
function rotationFor(index:number,count:number){if(count===2)return index===0?180:0;if(count===3)return index===0?180:index===1?90:-90;if(count===4)return index<2?180:0;return index%2===0?90:-90}
