import type { AICardTemplate, AICommanderTemplate } from '@/types/ai';

const C=(id:string,name:string,manaCost:number,power:number,toughness:number,color:string,oracleText?:string):AICardTemplate=>({id,name,manaCost,kind:'creature',typeLine:'Creature',power,toughness,colorIdentity:[color],oracleText});
export const AI_CARDS:AICardTemplate[]=[
 C('llanowar-elves','Llanowar Elves',1,1,1,'G','{T}: Add {G}.'),C('elvish-mystic','Elvish Mystic',1,1,1,'G','{T}: Add {G}.'),C('sakura-tribe-elder','Sakura-Tribe Elder',2,1,1,'G'),C('reclamation-sage','Reclamation Sage',3,2,1,'G'),C('eternal-witness','Eternal Witness',3,2,1,'G'),C('wood-elves','Wood Elves',3,1,1,'G'),C('beast-whisperer','Beast Whisperer',4,2,3,'G'),C('giant-spider','Giant Spider',4,2,4,'G','Reach'),C('acidic-slime','Acidic Slime',5,2,2,'G','Deathtouch'),C('thragtusk','Thragtusk',5,5,3,'G'),C('colossal-dreadmaw','Colossal Dreadmaw',6,6,6,'G','Trample'),C('carnage-tyrant','Carnage Tyrant',6,7,6,'G','Trample'),C('pelakka-wurm','Pelakka Wurm',7,7,7,'G','Trample'),
 {id:'naturalize',name:'Naturalize',manaCost:2,kind:'removal',typeLine:'Instant',oracleText:'Destroy target artifact or enchantment.',colorIdentity:['G']},
 C('cloudkin-seer','Cloudkin Seer',3,2,1,'U','Flying. When Cloudkin Seer enters the battlefield, draw a card.'),C('man-o-war','Man-o’-War',3,2,2,'U'),C('aven-fisher','Aven Fisher',4,2,2,'U','Flying'),C('air-elemental','Air Elemental',5,4,4,'U','Flying'),C('mulldrifter','Mulldrifter',5,2,2,'U','Flying'),C('prognostic-sphinx','Prognostic Sphinx',5,3,5,'U','Flying'),C('mahamoti-djinn','Mahamoti Djinn',6,5,6,'U','Flying'),C('sphinx-of-uthuun','Sphinx of Uthuun',7,5,6,'U','Flying'),
 {id:'divination',name:'Divination',manaCost:3,kind:'draw',typeLine:'Sorcery',oracleText:'Draw two cards.',amount:2,colorIdentity:['U']},{id:'inspiration',name:'Inspiration',manaCost:4,kind:'draw',typeLine:'Instant',oracleText:'Target player draws two cards.',amount:2,colorIdentity:['U']},
 C('soul-warden','Soul Warden',1,1,1,'W'),C('wall-of-omens','Wall of Omens',2,0,4,'W'),C('kor-cartographer','Kor Cartographer',4,2,2,'W'),C('palace-jailer','Palace Jailer',4,2,2,'W'),C('serra-angel','Serra Angel',5,4,4,'W','Flying, vigilance'),C('sun-titan','Sun Titan',6,6,6,'W','Vigilance'),C('angel-of-serenity','Angel of Serenity',7,5,6,'W','Flying'),
 {id:'pacifism',name:'Pacifism',manaCost:2,kind:'removal',typeLine:'Enchantment — Aura',oracleText:'Enchant creature. Enchanted creature can’t attack or block.',colorIdentity:['W']},{id:'disenchant',name:'Disenchant',manaCost:2,kind:'removal',typeLine:'Instant',oracleText:'Destroy target artifact or enchantment.',colorIdentity:['W']},
 C('goblin-instigator','Goblin Instigator',2,1,1,'R'),C('young-pyromancer','Young Pyromancer',2,2,1,'R'),C('goblin-chieftain','Goblin Chieftain',3,2,2,'R','Haste'),C('captain-lannery-storm','Captain Lannery Storm',3,2,2,'R','Haste'),C('hill-giant','Hill Giant',4,3,3,'R'),C('torbran','Torbran, Thane of Red Fell',4,2,4,'R'),C('siege-gang-commander','Siege-Gang Commander',5,2,2,'R'),C('shivan-dragon','Shivan Dragon',6,5,5,'R','Flying'),C('inferno-titan','Inferno Titan',6,6,6,'R'),C('balefire-dragon','Balefire Dragon',7,6,6,'R','Flying'),
 C('blood-artist','Blood Artist',2,0,1,'B'),C('gifted-aetherborn','Gifted Aetherborn',2,2,3,'B','Deathtouch, lifelink'),C('vampire-nighthawk','Vampire Nighthawk',3,2,3,'B','Flying, deathtouch, lifelink'),C('fleshbag-marauder','Fleshbag Marauder',3,3,1,'B'),C('solemn-simulacrum','Solemn Simulacrum',4,2,2,'B'),C('gray-merchant','Gray Merchant of Asphodel',5,2,4,'B'),C('grave-titan','Grave Titan',6,6,6,'B','Deathtouch'),C('noxious-gearhulk','Noxious Gearhulk',6,5,4,'B','Menace'),
 {id:'murder',name:'Murder',manaCost:3,kind:'removal',typeLine:'Instant',oracleText:'Destroy target creature.',colorIdentity:['B']},{id:'doom-blade',name:'Doom Blade',manaCost:2,kind:'removal',typeLine:'Instant',oracleText:'Destroy target nonblack creature.',colorIdentity:['B']},{id:'go-for-the-throat',name:'Go for the Throat',manaCost:2,kind:'removal',typeLine:'Instant',oracleText:'Destroy target nonartifact creature.',colorIdentity:['B']},{id:'sign-in-blood',name:'Sign in Blood',manaCost:2,kind:'draw',typeLine:'Sorcery',oracleText:'Target player draws two cards and loses 2 life.',amount:2,colorIdentity:['B']},
 {id:'mind-stone',name:'Mind Stone',manaCost:2,kind:'ramp',typeLine:'Artifact',oracleText:'{T}: Add {C}.',amount:1,colorIdentity:[]},{id:'arcane-signet',name:'Arcane Signet',manaCost:2,kind:'ramp',typeLine:'Artifact',oracleText:'{T}: Add one mana of any color in your commander’s color identity.',amount:1,colorIdentity:[]},{id:'fellwar-stone',name:'Fellwar Stone',manaCost:2,kind:'ramp',typeLine:'Artifact',oracleText:'{T}: Add one mana of any color that a land an opponent controls could produce.',amount:1,colorIdentity:[]},{id:'worn-powerstone',name:'Worn Powerstone',manaCost:3,kind:'ramp',typeLine:'Artifact',oracleText:'Worn Powerstone enters the battlefield tapped. {T}: Add {C}{C}.',amount:2,colorIdentity:[]}
];

export const AI_COMMANDERS:AICommanderTemplate[]=[
 {id:'talrand',name:'Talrand, Sky Summoner',manaCost:4,typeLine:'Legendary Creature — Merfolk Wizard',oracleText:'Whenever you cast an instant or sorcery spell, create a 2/2 blue Drake creature token with flying.',power:2,toughness:2,colorIdentity:['U']},
 {id:'krenko',name:'Krenko, Mob Boss',manaCost:4,typeLine:'Legendary Creature — Goblin Warrior',oracleText:'{T}: Create X 1/1 red Goblin creature tokens, where X is the number of Goblins you control.',power:3,toughness:3,colorIdentity:['R']},
 {id:'ayara',name:'Ayara, First of Locthwain',manaCost:3,typeLine:'Legendary Creature — Elf Noble',oracleText:'Whenever Ayara or another black creature enters under your control, each opponent loses 1 life and you gain 1 life.',power:2,toughness:3,colorIdentity:['B']},
 {id:'odric',name:'Odric, Lunarch Marshal',manaCost:4,typeLine:'Legendary Creature — Human Soldier',oracleText:'At the beginning of each combat, creatures you control gain abilities based on abilities among creatures you control.',power:3,toughness:3,colorIdentity:['W']},
 {id:'goreclaw',name:'Goreclaw, Terror of Qal Sisma',manaCost:4,typeLine:'Legendary Creature — Bear',oracleText:'Creature spells you cast with power 4 or greater cost {2} less to cast.',power:4,toughness:3,colorIdentity:['G']}
];
const BASIC_LANDS:Record<string,AICardTemplate>={W:{id:'plains',name:'Plains',manaCost:0,kind:'land',typeLine:'Basic Land — Plains',colorIdentity:['W']},U:{id:'island',name:'Island',manaCost:0,kind:'land',typeLine:'Basic Land — Island',colorIdentity:['U']},B:{id:'swamp',name:'Swamp',manaCost:0,kind:'land',typeLine:'Basic Land — Swamp',colorIdentity:['B']},R:{id:'mountain',name:'Mountain',manaCost:0,kind:'land',typeLine:'Basic Land — Mountain',colorIdentity:['R']},G:{id:'forest',name:'Forest',manaCost:0,kind:'land',typeLine:'Basic Land — Forest',colorIdentity:['G']}};
function shuffle<T>(items:T[]):T[]{const r=[...items];for(let i=r.length-1;i>0;i-=1){const j=Math.floor(Math.random()*(i+1));[r[i],r[j]]=[r[j],r[i]];}return r;}
function legalFor(card:AICardTemplate,identity:string[]){return(card.colorIdentity??[]).every(color=>identity.includes(color));}
export function buildCommanderAIDeck(){const commander=AI_COMMANDERS[Math.floor(Math.random()*AI_COMMANDERS.length)],pool=shuffle(AI_CARDS.filter(card=>legalFor(card,commander.colorIdentity))),land=BASIC_LANDS[commander.colorIdentity[0]],spellSlots=62;const spells=Array.from({length:spellSlots},(_,i)=>{const base=pool[i%pool.length];return{...base,id:`${base.id}-${i}`};});const basics=Array.from({length:37},(_,i)=>({...land,id:`${land.id}-${i}`}));return{commander,deck:shuffle([...spells,...basics])};}
export function buildRandomAIDeck():AICardTemplate[]{return buildCommanderAIDeck().deck;}
